# Generated by Django 3.2.7 on 2021-12-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(db_index=True, max_length=140, verbose_name='Body'),
        ),
    ]
